version: '3.9'

services:

  web:
    container_name: simple-web-app
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  redis:
    image: "redis:6.2.6-alpine"